---
title: 'Test and discuss workflows'
teaching: 60
exercises: 2
---

This section is dedicated to working on researchers’ workflows to prepare for deployment onto HPC systems. Group reflection is also included to identify issues and explore potential collaboration by sharing knowledge, including solutions and code. 

::: challenge
## Challenge: Test your workflows

In 20 minutes, work on your own workflows to: 

- Specify libraries and tools which need to be “transferred or prepared” for the HPC solution. 
- Experiment with transferring a simple workflow adopting the approach followed in the previous section. 
- Document the tasks which are performed at every stage. This will form the basis of the documentation you will need to provide. 
- Identify questions, issues that need resolving and pain points in the workflow. 

:::

::: challenge
## Challenge: Workflow collaboration

In 20 minutes, work in your groups to: 

- Identify and discuss the next steps to onboard your individual workflows to HPC. 
- Describe your workflow to your peers and investigate potential for sharing with them. 
- Examine how feasible it is to exchange solutions/code with your peers.  

:::
